# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_engine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='policy',
            new_name='rule_policy',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='rule_pkg',
        ),
        migrations.AddField(
            model_name='rulegroup',
            name='rule_group_policy',
            field=models.ManyToManyField(to='risk_engine.Policy'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule_pkg',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='rulegroup',
            name='rule_group_pkg',
            field=models.CharField(max_length=20),
        ),
    ]
