# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk_engine', '0003_auto_20180813_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='rule_flow_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='risk_engine.RuleGroup'),
        ),
    ]
