# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_engine', '0005_policy_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['product_name'],
            },
        ),
    ]
