# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk_engine', '0006_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_engine.Product'),
        ),
    ]
